# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_uygula_split = QtWidgets.QPushButton(self.tab)
        self.btn_uygula_split.setGeometry(QtCore.QRect(350, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_uygula_split.setFont(font)
        self.btn_uygula_split.setStyleSheet("")
        self.btn_uygula_split.setObjectName("btn_uygula_split")
        self.btn_open_file = QtWidgets.QPushButton(self.tab)
        self.btn_open_file.setGeometry(QtCore.QRect(340, 10, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_file.setFont(font)
        self.btn_open_file.setObjectName("btn_open_file")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(310, 110, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_file_name = QtWidgets.QLineEdit(self.tab)
        self.txt_file_name.setGeometry(QtCore.QRect(20, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_file_name.setFont(font)
        self.txt_file_name.setObjectName("txt_file_name")
        self.cmb_split = QtWidgets.QComboBox(self.tab)
        self.cmb_split.setGeometry(QtCore.QRect(20, 80, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cmb_split.setFont(font)
        self.cmb_split.setStyleSheet("")
        self.cmb_split.setObjectName("cmb_split")
        self.cmb_split.addItem("")
        self.cmb_split.addItem("")
        self.yuzde = QtWidgets.QLineEdit(self.tab)
        self.yuzde.setGeometry(QtCore.QRect(250, 110, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yuzde.setFont(font)
        self.yuzde.setStyleSheet("")
        self.yuzde.setObjectName("yuzde")
        self.btn_CLAHE = QtWidgets.QPushButton(self.tab)
        self.btn_CLAHE.setGeometry(QtCore.QRect(60, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_CLAHE.setFont(font)
        self.btn_CLAHE.setStyleSheet("")
        self.btn_CLAHE.setObjectName("btn_CLAHE")
        self.btn_HE = QtWidgets.QPushButton(self.tab)
        self.btn_HE.setGeometry(QtCore.QRect(220, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_HE.setFont(font)
        self.btn_HE.setStyleSheet("")
        self.btn_HE.setObjectName("btn_HE")
        self.btn_veriarttir = QtWidgets.QPushButton(self.tab)
        self.btn_veriarttir.setGeometry(QtCore.QRect(440, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_veriarttir.setFont(font)
        self.btn_veriarttir.setObjectName("btn_veriarttir")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cmb_CNN = QtWidgets.QComboBox(self.tab_2)
        self.cmb_CNN.setGeometry(QtCore.QRect(10, 10, 271, 22))
        self.cmb_CNN.setObjectName("cmb_CNN")
        self.cmb_CNN.addItem("")
        self.cmb_CNN.addItem("")
        self.btn_fit_CNN = QtWidgets.QPushButton(self.tab_2)
        self.btn_fit_CNN.setGeometry(QtCore.QRect(300, 10, 75, 23))
        self.btn_fit_CNN.setObjectName("btn_fit_CNN")
        self.btn_predict_CNN = QtWidgets.QPushButton(self.tab_2)
        self.btn_predict_CNN.setGeometry(QtCore.QRect(380, 10, 75, 23))
        self.btn_predict_CNN.setObjectName("btn_predict_CNN")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 40, 941, 271))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 531, 231))
        self.label_2.setObjectName("label_2")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.listWidget = QtWidgets.QListWidget(self.tab_4)
        self.listWidget.setGeometry(QtCore.QRect(220, 20, 256, 192))
        self.listWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.listWidget.setObjectName("listWidget")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lb_roc1 = QtWidgets.QLabel(self.tab_5)
        self.lb_roc1.setGeometry(QtCore.QRect(20, 20, 881, 201))
        self.lb_roc1.setObjectName("lb_roc1")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_sens = QtWidgets.QWidget()
        self.tab_sens.setObjectName("tab_sens")
        self.tabWidget_2.addTab(self.tab_sens, "")
        self.tab_model = QtWidgets.QWidget()
        self.tab_model.setObjectName("tab_model")
        self.btn_resimSec = QtWidgets.QPushButton(self.tab_model)
        self.btn_resimSec.setGeometry(QtCore.QRect(170, 100, 131, 23))
        self.btn_resimSec.setObjectName("btn_resimSec")
        self.label_class = QtWidgets.QLabel(self.tab_model)
        self.label_class.setGeometry(QtCore.QRect(550, 100, 301, 16))
        self.label_class.setObjectName("label_class")
        self.tabWidget_2.addTab(self.tab_model, "")
        self.btn_savemodelCNN = QtWidgets.QPushButton(self.tab_2)
        self.btn_savemodelCNN.setGeometry(QtCore.QRect(460, 10, 131, 23))
        self.btn_savemodelCNN.setObjectName("btn_savemodelCNN")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.cmb_CNN_1 = QtWidgets.QComboBox(self.tab_6)
        self.cmb_CNN_1.setGeometry(QtCore.QRect(40, 10, 271, 31))
        self.cmb_CNN_1.setObjectName("cmb_CNN_1")
        self.cmb_CNN_1.addItem("")
        self.cmb_CNN_1.addItem("")
        self.cmb_machine = QtWidgets.QComboBox(self.tab_6)
        self.cmb_machine.setGeometry(QtCore.QRect(420, 10, 271, 31))
        self.cmb_machine.setObjectName("cmb_machine")
        self.cmb_machine.addItem("")
        self.cmb_machine.addItem("")
        self.btn_fit_CNN_2 = QtWidgets.QPushButton(self.tab_6)
        self.btn_fit_CNN_2.setGeometry(QtCore.QRect(700, 12, 75, 31))
        self.btn_fit_CNN_2.setObjectName("btn_fit_CNN_2")
        self.btn_predict_CNN_2 = QtWidgets.QPushButton(self.tab_6)
        self.btn_predict_CNN_2.setGeometry(QtCore.QRect(790, 12, 75, 31))
        self.btn_predict_CNN_2.setObjectName("btn_predict_CNN_2")
        self.label = QtWidgets.QLabel(self.tab_6)
        self.label.setGeometry(QtCore.QRect(0, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setGeometry(QtCore.QRect(320, 20, 91, 16))
        self.label_4.setObjectName("label_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 60, 961, 251))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(180, 0, 591, 221))
        self.label_3.setObjectName("label_3")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_8)
        self.listWidget_3.setGeometry(QtCore.QRect(180, 20, 256, 192))
        self.listWidget_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.listWidget_3.setObjectName("listWidget_3")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.lb_roc2 = QtWidgets.QLabel(self.tab_9)
        self.lb_roc2.setGeometry(QtCore.QRect(0, 0, 711, 181))
        self.lb_roc2.setObjectName("lb_roc2")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_sensM = QtWidgets.QWidget()
        self.tab_sensM.setObjectName("tab_sensM")
        self.tabWidget_3.addTab(self.tab_sensM, "")
        self.tab_modeltestM = QtWidgets.QWidget()
        self.tab_modeltestM.setObjectName("tab_modeltestM")
        self.btn_resimSecTF = QtWidgets.QPushButton(self.tab_modeltestM)
        self.btn_resimSecTF.setGeometry(QtCore.QRect(220, 80, 131, 23))
        self.btn_resimSecTF.setObjectName("btn_resimSecTF")
        self.label_classTF = QtWidgets.QLabel(self.tab_modeltestM)
        self.label_classTF.setGeometry(QtCore.QRect(570, 80, 351, 20))
        self.label_classTF.setObjectName("label_classTF")
        self.tabWidget_3.addTab(self.tab_modeltestM, "")
        self.btn_savemodelM = QtWidgets.QPushButton(self.tab_6)
        self.btn_savemodelM.setGeometry(QtCore.QRect(720, 50, 131, 23))
        self.btn_savemodelM.setObjectName("btn_savemodelM")
        self.tabWidget.addTab(self.tab_6, "")
        self.termenal = QtWidgets.QListWidget(self.centralwidget)
        self.termenal.setGeometry(QtCore.QRect(0, 340, 1071, 171))
        self.termenal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.termenal.setObjectName("termenal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(3)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_uygula_split.setText(_translate("MainWindow", "Uygula"))
        self.btn_open_file.setText(_translate("MainWindow", "Open File"))
        self.label_9.setText(_translate("MainWindow", "%"))
        self.label_5.setText(_translate("MainWindow", "Test için ayırmak istediğiniz kısım :"))
        self.cmb_split.setCurrentText(_translate("MainWindow", "Hold Out"))
        self.cmb_split.setItemText(0, _translate("MainWindow", "Hold Out"))
        self.cmb_split.setItemText(1, _translate("MainWindow", "K-Fold"))
        self.btn_CLAHE.setText(_translate("MainWindow", "CLAHE"))
        self.btn_HE.setText(_translate("MainWindow", "HE"))
        self.btn_veriarttir.setText(_translate("MainWindow", "Veri Arttır"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Veri"))
        self.cmb_CNN.setItemText(0, _translate("MainWindow", "VGG16"))
        self.cmb_CNN.setItemText(1, _translate("MainWindow", "AlexNet"))
        self.btn_fit_CNN.setText(_translate("MainWindow", "fit"))
        self.btn_predict_CNN.setText(_translate("MainWindow", "predict"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", " Accuracy – Loss grafik"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Karışıklık Matris"))
        self.lb_roc1.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", " ROC eğrisi grafik"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_sens), _translate("MainWindow", "Page"))
        self.btn_resimSec.setText(_translate("MainWindow", "Resim Seç Ve Test Et"))
        self.label_class.setText(_translate("MainWindow", "Sınıf"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_model), _translate("MainWindow", "Önceden kaydedilen modeli çağır ve test et"))
        self.btn_savemodelCNN.setText(_translate("MainWindow", "modeli kaydet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "CNN"))
        self.cmb_CNN_1.setItemText(0, _translate("MainWindow", "VGG16"))
        self.cmb_CNN_1.setItemText(1, _translate("MainWindow", "AlexNet"))
        self.cmb_machine.setItemText(0, _translate("MainWindow", "KNN"))
        self.cmb_machine.setItemText(1, _translate("MainWindow", "Random Forest"))
        self.btn_fit_CNN_2.setText(_translate("MainWindow", "fit"))
        self.btn_predict_CNN_2.setText(_translate("MainWindow", "predict"))
        self.label.setText(_translate("MainWindow", "CNN :"))
        self.label_4.setText(_translate("MainWindow", "Machine Learning :"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", " Accuracy – Loss grafik"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Karışıklık Matris"))
        self.lb_roc2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", " ROC eğrisi grafik"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_sensM), _translate("MainWindow", "Page"))
        self.btn_resimSecTF.setText(_translate("MainWindow", "Resim Seç Ve Test Et"))
        self.label_classTF.setText(_translate("MainWindow", "Sınıf"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_modeltestM), _translate("MainWindow", "Önceden kaydedilen modeli çağır ve test et"))
        self.btn_savemodelM.setText(_translate("MainWindow", "modeli kaydet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "CNN with Machine Learning"))

